# Generated by Django 4.0 on 2022-02-11 12:29

import anpr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anpr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=anpr_app.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
