# Generated by Django 4.0 on 2022-02-12 14:34

import anpr_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anpr_app', '0002_imageupload_alter_vehicleowner_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.ImageField(upload_to=anpr_app.models.upload_to)),
                ('img', models.ImageField(upload_to=anpr_app.models.upload_to)),
            ],
        ),
    ]
