# Generated by Django 4.0 on 2022-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anpr_app', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='photo', editable=False, max_length=5),
        ),
    ]
