# Generated by Django 4.0 on 2022-02-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anpr_app', '0004_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='photo', max_length=5),
        ),
    ]
